[server]
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
port = 10000

[browser]
serverAddress = "ecommerce-kt-rag.onrender.com"
serverPort = 443
gatherUsageStats = false
